### ISSUE TITLE
Spacelens - Whitelist

### ISSUE THREAD

**Issue by nathanaeleisenberg** [kswap-finance/kswap-tech#2]
As per instructions, we would like to add the following to Whitelist:

Project: Spacelens
Token: SPACE
Etherscan contract address: 0xcc7ab8d78dba187dc95bf3bb86e65e0c26d0041f
Website: https://spacetoken.spacelens.com

**Comment by xbc-main** [comment]
Hi. Pls submit your issue on https://github.com/kswap-finance/static/issues
